nodeLinker: node-modules
enableImmutableInstalls: false
packageExtensions:
  "@eslint/js@*":
    peerDependencies:
      eslint: "*"
  "eslint-plugin-react-hooks@*":
    peerDependencies:
      eslint: "*"
  "eslint-plugin-react-refresh@*":
    peerDependencies:
      eslint: "*"
  "typescript-eslint@*":
    peerDependencies:
      eslint: "*"
      typescript: "*"
